language: php

php:
  - 5.6
  - 7.1

services:
  - mysql

env:
  global:
    - PLUGIN_NAME=MasterReplica
    - REQUIRE=""
    - DB=mysql
    - COMPOSER_HOME=/home/travis/.composer

  matrix:
    - CAKE_REF=2.7.11
    - CAKE_REF=2.8.9
    - CAKE_REF=2.9.9
    - CAKE_REF=2.10.18

matrix:
  include:
    - php: 7.2
      env:
        - USE_PHPUNIT_5=1
        - CAKE_REF=2.10.18
    - php: 7.3
      env:
        - USE_PHPUNIT_5=1
        - CAKE_REF=2.10.18
    - php: 7.3
      env:
        - PHPCS=1

before_script:
  - travis_wait ./travis_before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
